version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/restaurant_service
    ports:
      - "8000:8000"
    depends_on:
      - db
